_target_: temos.callback.VizCheckPoint

start_epoch: ${viz_metrics_start_epoch}
filename: viz-{epoch}
dirpath: ${path.working_dir}/checkpoints
monitor: step
mode: max
every_n_epochs: ${viz_metrics_every_n_epoch}
save_top_k: -1
save_last: false
save_weights_only: true
