_target_: temos.callback.VizCheckPoint

start_epoch: 100
filename: viz-{epoch}
dirpath: ${path.working_dir}/checkpoints
monitor: step
mode: max
every_n_epochs: 5
save_top_k: -1
save_last: false
save_weights_only: true
