hydra:
  run:
    dir: .
  output_subdir: null

logger_level: INFO
folder: ???

defaults:
  - /path@path

datapath: ${path.datasets} #not /kit
splitpath: ${path.datasets}/kit-splits
split: recons
vocab_size: 1000
sk_type: kitml

gt: xyz_data.pkl
contiguous_frame2cluster_mapping: contiguous_frame2cluster_mapping.pkl
cluster2keypoint_mapping: proxy_centers_tr_${vocab_size}.pkl
cluster2frame_mapping: proxy_centers_tr_complete_${vocab_size}.pkl

fps: 25.0 #desired fps for mpjpe calculation and visualization
recons_fps: 12.5 #same as fps of predictions
gt_fps: 100.0 #fps of KIT

visualize: True
force: False
viz_dir: reconstructions # folder/viz_dir

visualize_gt: True
force_gt: False
viz_gt_dir: constructions # datapath/viz_gt_dir