hydra:
  run:
    dir: outputs/${data.dataname}/${experiment}/${run_id}

# Global configurations shared between different modules
experiment: asymov

seed: 1234

logger_level: INFO
run_id: ${generate_id:}
resume_ckpt_path:
wandb_api_keys:
  darsh: 57f6d5aab6f1a78b78fb181dcf32dfeca0e65f79
  arjun: bac3a003428df951a8e0b9e3878002a3227bbf0c
user: 

# Composing nested config with default
defaults:
  - data: kit-xyz-motion-word
  - model: asymov
  - machine: server
  - trainer: gpu
  - sampler: variable_conseq
  - logger: wandb
  - callback: base
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  transforms:
    normalization: true

callback:
  viz_ckpts: true 

transforms: ${data.transforms}
